apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o ./k8s
    kompose.version: 1.21.0 (992df58d8)
  labels:
    io.kompose.service: jaeger
  name: jaeger
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: jaeger
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -o ./k8s
        kompose.version: 1.21.0 (992df58d8)
      labels:
        io.kompose.network/net: "true"
        io.kompose.service: jaeger
    spec:
      containers:
      - env:
        - name: ES_SERVER_URLS
          value: http://elasticsearch:9200
        - name: ES_TAGS_AS_FIELDS_ALL
          value: "true"
        - name: SPAN_STORAGE_TYPE
          value: elasticsearch
        image: jaegertracing/all-in-one:1.19.2
        imagePullPolicy: ""
        name: jaeger
        ports:
        - containerPort: 6831
          protocol: UDP
        - containerPort: 16686
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
