apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o ./k8s
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: kafdrop
  name: kafdrop
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: kafdrop
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -o ./k8s
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.network/net: "true"
        io.kompose.service: kafdrop
    spec:
      containers:
      - env:
        - name: JVM_OPTS
          value: -Xms32M -Xmx64M
        - name: KAFKA_BROKERCONNECT
          value: kafka:29092
        - name: SERVER_PORT
          value: "9050"
        - name: SERVER_SERVLET_CONTEXTPATH
          value: /
        image: obsidiandynamics/kafdrop:3.27.0
        imagePullPolicy: ""
        name: kafdrop
        ports:
        - containerPort: 9050
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
