apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -o ./k8s
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: kotlin-sample-card
  name: kotlin-sample-card
spec:
  ports:
  - name: "8190"
    port: 8190
    targetPort: 8090
  selector:
    io.kompose.service: kotlin-sample-card
status:
  loadBalancer: {}
