global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: [ 'localhost:9090' ]
        labels:
          instance: prometheus

  - job_name: kotlin-sample-card
    metrics_path: '/kotlin-sample-card/v1/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: [ '172.17.0.1:8090' ] # change for the docker host IP → user ifconfig and get the IP associated with docker0. obs: prometheus config file DOES NOT support environment variables
        labels:
          instance: kotlin-sample-card

  - job_name: rabbitmq
    metrics_path: '/metrics'
    scrape_interval: 5s
    static_configs:
      - targets: [ 'rabbitmq:15692' ]
        labels:
          instance: rabbitmq
